-- Execute in Supabase SQL Editor once. No public registration/admin assignment.
begin;
create table if not exists public.celvis_admins (
 user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.celvis_admins enable row level security;
revoke all on public.celvis_admins from anon, authenticated;
grant select on public.celvis_admins to authenticated;
drop policy if exists admin_own_membership on public.celvis_admins;
create policy admin_own_membership on public.celvis_admins for select to authenticated using (user_id = (select auth.uid()));
create table if not exists public.repair_prices (
 id bigint generated always as identity primary key,
 model text not null check (length(model) between 1 and 100),
 service text not null check (length(service) between 1 and 120),
 amount numeric(10,2),
 price_mode text not null default 'quote' check (price_mode in ('fixed','from','quote')),
 note text not null default '' check (length(note) <= 300),
 enabled boolean not null default true,
 sort_order integer not null default 0,
 version bigint not null default 1,
 updated_at timestamptz not null default now(),
 unique(model,service),
 check ((price_mode='quote' and amount is null) or (price_mode in ('fixed','from') and amount between 0 and 1000000))
);
alter table public.repair_prices enable row level security;
revoke all on public.repair_prices from anon, authenticated;
grant select on public.repair_prices to anon, authenticated;
grant insert, update on public.repair_prices to authenticated;
grant usage, select on sequence public.repair_prices_id_seq to authenticated;
drop policy if exists public_visible_prices on public.repair_prices;
create policy public_visible_prices on public.repair_prices for select to anon, authenticated using (enabled);
drop policy if exists admin_read_prices on public.repair_prices;
create policy admin_read_prices on public.repair_prices for select to authenticated using (exists(select 1 from public.celvis_admins where user_id=(select auth.uid())));
drop policy if exists admin_insert_prices on public.repair_prices;
create policy admin_insert_prices on public.repair_prices for insert to authenticated with check (exists(select 1 from public.celvis_admins where user_id=(select auth.uid())));
drop policy if exists admin_update_prices on public.repair_prices;
create policy admin_update_prices on public.repair_prices for update to authenticated using (exists(select 1 from public.celvis_admins where user_id=(select auth.uid()))) with check (exists(select 1 from public.celvis_admins where user_id=(select auth.uid())));
create or replace function public.bump_price_version() returns trigger language plpgsql set search_path = public as $$
begin
 new.version = old.version + 1;
 new.updated_at = now();
 return new;
end;
$$;
drop trigger if exists price_version on public.repair_prices;
create trigger price_version before update on public.repair_prices for each row execute function public.bump_price_version();
insert into public.repair_prices(model,service,amount,price_mode,note,sort_order) values
('iPhone XR','Pantalla Incell',2800,'fixed','Garantía incluida',0),
('iPhone XR','Batería',2000,'fixed','Instalación incluida',1),
('iPhone XR','Tapa trasera',2500,'from','Según color',2),
('iPhone XR','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',3),
('iPhone XR','Face ID',null,'quote','Confirmar disponibilidad',4),
('iPhone XR','Microsoldadura',null,'quote','Confirmar disponibilidad',5),
('iPhone 11','Pantalla Incell',2800,'fixed','Garantía incluida',100),
('iPhone 11','Batería',2200,'fixed','Instalación incluida',101),
('iPhone 11','Face ID',3500,'from','Requiere diagnóstico',102),
('iPhone 11','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',103),
('iPhone 11','Tapa trasera',null,'quote','Confirmar disponibilidad',104),
('iPhone 11','Microsoldadura',null,'quote','Confirmar disponibilidad',105),
('iPhone 11 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',200),
('iPhone 11 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',201),
('iPhone 11 Pro','Batería',null,'quote','Confirmar disponibilidad',202),
('iPhone 11 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',203),
('iPhone 11 Pro','Face ID',null,'quote','Confirmar disponibilidad',204),
('iPhone 11 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',205),
('iPhone 11 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',300),
('iPhone 11 Pro Max','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',301),
('iPhone 11 Pro Max','Batería',null,'quote','Confirmar disponibilidad',302),
('iPhone 11 Pro Max','Tapa trasera',null,'quote','Confirmar disponibilidad',303),
('iPhone 11 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',304),
('iPhone 11 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',305),
('iPhone 12','Pantalla Incell',null,'quote','Confirmar disponibilidad',400),
('iPhone 12','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',401),
('iPhone 12','Batería',null,'quote','Confirmar disponibilidad',402),
('iPhone 12','Tapa trasera',null,'quote','Confirmar disponibilidad',403),
('iPhone 12','Face ID',null,'quote','Confirmar disponibilidad',404),
('iPhone 12','Microsoldadura',null,'quote','Confirmar disponibilidad',405),
('iPhone 12 Mini','Pantalla Incell',null,'quote','Confirmar disponibilidad',500),
('iPhone 12 Mini','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',501),
('iPhone 12 Mini','Batería',null,'quote','Confirmar disponibilidad',502),
('iPhone 12 Mini','Tapa trasera',null,'quote','Confirmar disponibilidad',503),
('iPhone 12 Mini','Face ID',null,'quote','Confirmar disponibilidad',504),
('iPhone 12 Mini','Microsoldadura',null,'quote','Confirmar disponibilidad',505),
('iPhone 12 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',600),
('iPhone 12 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',601),
('iPhone 12 Pro','Batería',null,'quote','Confirmar disponibilidad',602),
('iPhone 12 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',603),
('iPhone 12 Pro','Face ID',null,'quote','Confirmar disponibilidad',604),
('iPhone 12 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',605),
('iPhone 12 Pro Max','Pantalla Soft OLED',6500,'fixed','Garantía incluida',700),
('iPhone 12 Pro Max','Batería Premium',3500,'fixed','Instalación incluida',701),
('iPhone 12 Pro Max','Tapa trasera',3500,'from','Según color',702),
('iPhone 12 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',703),
('iPhone 12 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',704),
('iPhone 12 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',705),
('iPhone 13','Pantalla Incell',null,'quote','Confirmar disponibilidad',800),
('iPhone 13','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',801),
('iPhone 13','Batería',null,'quote','Confirmar disponibilidad',802),
('iPhone 13','Tapa trasera',null,'quote','Confirmar disponibilidad',803),
('iPhone 13','Face ID',null,'quote','Confirmar disponibilidad',804),
('iPhone 13','Microsoldadura',null,'quote','Confirmar disponibilidad',805),
('iPhone 13 Mini','Pantalla Incell',null,'quote','Confirmar disponibilidad',900),
('iPhone 13 Mini','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',901),
('iPhone 13 Mini','Batería',null,'quote','Confirmar disponibilidad',902),
('iPhone 13 Mini','Tapa trasera',null,'quote','Confirmar disponibilidad',903),
('iPhone 13 Mini','Face ID',null,'quote','Confirmar disponibilidad',904),
('iPhone 13 Mini','Microsoldadura',null,'quote','Confirmar disponibilidad',905),
('iPhone 13 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',1000),
('iPhone 13 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1001),
('iPhone 13 Pro','Batería',null,'quote','Confirmar disponibilidad',1002),
('iPhone 13 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',1003),
('iPhone 13 Pro','Face ID',null,'quote','Confirmar disponibilidad',1004),
('iPhone 13 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',1005),
('iPhone 13 Pro Max','Pantalla Soft OLED',8000,'fixed','Garantía incluida',1100),
('iPhone 13 Pro Max','Batería',3800,'fixed','Instalación incluida',1101),
('iPhone 13 Pro Max','Microsoldadura',3500,'from','Según diagnóstico',1102),
('iPhone 13 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',1103),
('iPhone 13 Pro Max','Tapa trasera',null,'quote','Confirmar disponibilidad',1104),
('iPhone 13 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',1105),
('iPhone 14','Pantalla Incell',null,'quote','Confirmar disponibilidad',1200),
('iPhone 14','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1201),
('iPhone 14','Batería',null,'quote','Confirmar disponibilidad',1202),
('iPhone 14','Tapa trasera',null,'quote','Confirmar disponibilidad',1203),
('iPhone 14','Face ID',null,'quote','Confirmar disponibilidad',1204),
('iPhone 14','Microsoldadura',null,'quote','Confirmar disponibilidad',1205),
('iPhone 14 Plus','Pantalla Incell',null,'quote','Confirmar disponibilidad',1300),
('iPhone 14 Plus','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1301),
('iPhone 14 Plus','Batería',null,'quote','Confirmar disponibilidad',1302),
('iPhone 14 Plus','Tapa trasera',null,'quote','Confirmar disponibilidad',1303),
('iPhone 14 Plus','Face ID',null,'quote','Confirmar disponibilidad',1304),
('iPhone 14 Plus','Microsoldadura',null,'quote','Confirmar disponibilidad',1305),
('iPhone 14 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',1400),
('iPhone 14 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1401),
('iPhone 14 Pro','Batería',null,'quote','Confirmar disponibilidad',1402),
('iPhone 14 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',1403),
('iPhone 14 Pro','Face ID',null,'quote','Confirmar disponibilidad',1404),
('iPhone 14 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',1405),
('iPhone 14 Pro Max','Pantalla Soft OLED',9500,'fixed','Garantía incluida',1500),
('iPhone 14 Pro Max','Batería',4500,'fixed','Instalación incluida',1501),
('iPhone 14 Pro Max','Conversión SIM física',null,'quote','Servicio especializado',1502),
('iPhone 14 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',1503),
('iPhone 14 Pro Max','Tapa trasera',null,'quote','Confirmar disponibilidad',1504),
('iPhone 14 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',1505),
('iPhone 14 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',1506),
('iPhone 15','Pantalla Incell',null,'quote','Confirmar disponibilidad',1600),
('iPhone 15','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1601),
('iPhone 15','Batería',null,'quote','Confirmar disponibilidad',1602),
('iPhone 15','Tapa trasera',null,'quote','Confirmar disponibilidad',1603),
('iPhone 15','Face ID',null,'quote','Confirmar disponibilidad',1604),
('iPhone 15','Microsoldadura',null,'quote','Confirmar disponibilidad',1605),
('iPhone 15 Plus','Pantalla Incell',null,'quote','Confirmar disponibilidad',1700),
('iPhone 15 Plus','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1701),
('iPhone 15 Plus','Batería',null,'quote','Confirmar disponibilidad',1702),
('iPhone 15 Plus','Tapa trasera',null,'quote','Confirmar disponibilidad',1703),
('iPhone 15 Plus','Face ID',null,'quote','Confirmar disponibilidad',1704),
('iPhone 15 Plus','Microsoldadura',null,'quote','Confirmar disponibilidad',1705),
('iPhone 15 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',1800),
('iPhone 15 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1801),
('iPhone 15 Pro','Batería',null,'quote','Confirmar disponibilidad',1802),
('iPhone 15 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',1803),
('iPhone 15 Pro','Face ID',null,'quote','Confirmar disponibilidad',1804),
('iPhone 15 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',1805),
('iPhone 15 Pro Max','Pantalla',null,'quote','Varias calidades',1900),
('iPhone 15 Pro Max','Tapa trasera',null,'quote','Según disponibilidad',1901),
('iPhone 15 Pro Max','Conversión SIM física',3500,'from','Servicio especializado',1902),
('iPhone 15 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',1903),
('iPhone 15 Pro Max','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',1904),
('iPhone 15 Pro Max','Batería',null,'quote','Confirmar disponibilidad',1905),
('iPhone 15 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',1906),
('iPhone 15 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',1907),
('iPhone 16','Pantalla Incell',null,'quote','Confirmar disponibilidad',2000),
('iPhone 16','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2001),
('iPhone 16','Batería',null,'quote','Confirmar disponibilidad',2002),
('iPhone 16','Tapa trasera',null,'quote','Confirmar disponibilidad',2003),
('iPhone 16','Face ID',null,'quote','Confirmar disponibilidad',2004),
('iPhone 16','Microsoldadura',null,'quote','Confirmar disponibilidad',2005),
('iPhone 16 Plus','Pantalla Incell',null,'quote','Confirmar disponibilidad',2100),
('iPhone 16 Plus','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2101),
('iPhone 16 Plus','Batería',null,'quote','Confirmar disponibilidad',2102),
('iPhone 16 Plus','Tapa trasera',null,'quote','Confirmar disponibilidad',2103),
('iPhone 16 Plus','Face ID',null,'quote','Confirmar disponibilidad',2104),
('iPhone 16 Plus','Microsoldadura',null,'quote','Confirmar disponibilidad',2105),
('iPhone 16 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',2200),
('iPhone 16 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2201),
('iPhone 16 Pro','Batería',null,'quote','Confirmar disponibilidad',2202),
('iPhone 16 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',2203),
('iPhone 16 Pro','Face ID',null,'quote','Confirmar disponibilidad',2204),
('iPhone 16 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',2205),
('iPhone 16 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',2300),
('iPhone 16 Pro Max','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2301),
('iPhone 16 Pro Max','Batería',null,'quote','Confirmar disponibilidad',2302),
('iPhone 16 Pro Max','Tapa trasera',null,'quote','Confirmar disponibilidad',2303),
('iPhone 16 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',2304),
('iPhone 16 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',2305),
('iPhone 17','Pantalla Incell',null,'quote','Confirmar disponibilidad',2400),
('iPhone 17','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2401),
('iPhone 17','Batería',null,'quote','Confirmar disponibilidad',2402),
('iPhone 17','Tapa trasera',null,'quote','Confirmar disponibilidad',2403),
('iPhone 17','Face ID',null,'quote','Confirmar disponibilidad',2404),
('iPhone 17','Microsoldadura',null,'quote','Confirmar disponibilidad',2405),
('iPhone 17 Air','Pantalla Incell',null,'quote','Confirmar disponibilidad',2500),
('iPhone 17 Air','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2501),
('iPhone 17 Air','Batería',null,'quote','Confirmar disponibilidad',2502),
('iPhone 17 Air','Tapa trasera',null,'quote','Confirmar disponibilidad',2503),
('iPhone 17 Air','Face ID',null,'quote','Confirmar disponibilidad',2504),
('iPhone 17 Air','Microsoldadura',null,'quote','Confirmar disponibilidad',2505),
('iPhone 17 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',2600),
('iPhone 17 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2601),
('iPhone 17 Pro','Batería',null,'quote','Confirmar disponibilidad',2602),
('iPhone 17 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',2603),
('iPhone 17 Pro','Face ID',null,'quote','Confirmar disponibilidad',2604),
('iPhone 17 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',2605),
('iPhone 17 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',2700),
('iPhone 17 Pro Max','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2701),
('iPhone 17 Pro Max','Batería',null,'quote','Confirmar disponibilidad',2702),
('iPhone 17 Pro Max','Tapa trasera',null,'quote','Confirmar disponibilidad',2703),
('iPhone 17 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',2704),
('iPhone 17 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',2705),
('iPhone 18 Pro','Pantalla Incell',null,'quote','Confirmar disponibilidad',2800),
('iPhone 18 Pro','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2801),
('iPhone 18 Pro','Batería',null,'quote','Confirmar disponibilidad',2802),
('iPhone 18 Pro','Tapa trasera',null,'quote','Confirmar disponibilidad',2803),
('iPhone 18 Pro','Face ID',null,'quote','Confirmar disponibilidad',2804),
('iPhone 18 Pro','Microsoldadura',null,'quote','Confirmar disponibilidad',2805),
('iPhone 18 Pro Max','Pantalla Incell',null,'quote','Confirmar disponibilidad',2900),
('iPhone 18 Pro Max','Pantalla Soft OLED',null,'quote','Confirmar disponibilidad',2901),
('iPhone 18 Pro Max','Batería',null,'quote','Confirmar disponibilidad',2902),
('iPhone 18 Pro Max','Tapa trasera',null,'quote','Confirmar disponibilidad',2903),
('iPhone 18 Pro Max','Face ID',null,'quote','Confirmar disponibilidad',2904),
('iPhone 18 Pro Max','Microsoldadura',null,'quote','Confirmar disponibilidad',2905)
on conflict(model,service) do nothing;
commit;

-- AFTER creating your Auth user, paste its UUID below and run separately:
-- insert into public.celvis_admins(user_id) values ('YOUR_AUTH_USER_UUID') on conflict do nothing;
